@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@username = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}

### Bienvenida
GET {{root}}

### Autorizacion
# @name auth
POST {{root}}/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### GET Distritos
GET {{baseUrl}}/distritos
Authorization: Bearer {{auth.response.body.access_token}}

### GET Oficinas del Distrito
GET {{baseUrl}}/oficinas
    ?distrito_id=6
Authorization: Bearer {{auth.response.body.access_token}}

### Oficina 71 J TERCERO FAMILIAR SALTILLO
GET {{baseUrl}}/oficinas/71
Authorization: Bearer {{auth.response.body.access_token}}

### GET Servicios de la Oficina
GET {{baseUrl}}/cit_oficinas_servicios
    ?oficina_id=71
Authorization: Bearer {{auth.response.body.access_token}}

### GET Dias para elegir
GET {{baseUrl}}/cit_dias_disponibles
    ?oficina_id=71
Authorization: Bearer {{auth.response.body.access_token}}

### GET Horas para elegir
GET {{baseUrl}}/cit_horas_disponibles
    ?oficina_id=71
    &cit_servicio_id=2
    &fecha=2022-08-09
Authorization: Bearer {{auth.response.body.access_token}}

### POST crear cita
POST {{baseUrl}}/cit_citas/nueva
Authorization: Bearer {{auth.response.body.access_token}}
content-type: application/json

{
    "oficina_id": 71,
    "cit_servicio_id": 2,
    "fecha": "2022-08-09",
    "hora_minuto": "09:15"
}

### GET mis citas
GET {{baseUrl}}/cit_citas
Authorization: Bearer {{auth.response.body.access_token}}

### GET consultar una cita
GET {{baseUrl}}/cit_citas/consultar
    ?cit_cita_id=1299
Authorization: Bearer {{auth.response.body.access_token}}

### GET cancelar una cita
GET {{baseUrl}}/cit_citas/cancelar
    ?cit_cita_id=1299
Authorization: Bearer {{auth.response.body.access_token}}
