@root = http://{{$dotenv HOST}}:{{$dotenv PORT}}
@baseUrl = {{root}}/v2

### Bienvenida
GET {{root}}

### Quiero crear una nueva cuenta, recibo el formulario con los datos personales
POST {{baseUrl}}/cit_clientes_registros
content-type: application/json

{
    "nombres": "Pedro",
    "apellido_primero": "Infante",
    "apellido_segundo": "CRUZ",
    "curp": "VADJ770826HGRRLS34",
    "telefono": "8443331122",
    "email": "pedro.infante@gmail.com"
}

### Quiero crear una nueva cuenta, entrego el formulario para definir la contrasena
@hashid = XXXX
@cadena_validar = XXXX

GET {{baseUrl}}/cit_clientes_registros
    ?id={{hashid}}
    &cadena_validar={{cadena_validar}}

### Quiero crear una nueva cuenta, recibo el formulario con la contrasena
POST {{baseUrl}}/cit_clientes_registros
content-type: application/json

{
    "id": "{{hashid}}",
    "cadena_validar": "{{cadena_validar}}",
    "password": "Zebra13Blanca"
}
