@root = http://{{$dotenv HOST}}:{{$dotenv PORT}}
@baseUrl = {{root}}/v1
@username = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}

### Bienvenida
GET {{root}}

### Quiero crear una nueva cuenta
POST {{baseUrl}}/cit_clientes_registros
content-type: application/json

{
    "nombres": "Pedro",
    "apellido_primero": "Infante",
    "apellido_segundo": "CRUZ",
    "curp": "VADJ770826HGRRLS34",
    "telefono": "8443331122",
    "email": "pedro.infante@gmail.com"
}

### Olvide mi contrasena
POST {{baseUrl}}/cit_clientes_recuperaciones
content-type: application/json

{
    "email": "guivaloz@gmail.com"
}

### Autorizacion
# @name auth
POST {{root}}/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}
