@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@username = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}

### Bienvenida
GET {{root}}

### Autorizacion
# @name auth
POST {{root}}/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Perfil
GET {{root}}/profile
Authorization: Bearer {{auth.response.body.access_token}}

### Cantidad de citas disponibles
GET {{baseUrl}}/cit_citas/disponibles
Authorization: Bearer {{auth.response.body.access_token}}
