@root = http://{{$dotenv HOST}}:{{$dotenv PORT}}
@baseUrl = {{root}}
@username = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}

### Bienvenida
GET {{root}}

### Autorizacion
# @name auth
POST {{baseUrl}}/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### GET Tramites y Servicios
GET {{baseUrl}}/v2/cit_tramites_servicios
Authorization: Bearer {{auth.response.body.access_token}}

### GET Tramites y Servicios - Curso de Preparacion en Materia de Mediacion
GET {{baseUrl}}/v2/cit_tramites_servicios/2
Authorization: Bearer {{auth.response.body.access_token}}

### POST Pago antes del banco, recibe los datos del asistente en React.js, entrega el id del pago
POST {{baseUrl}}/v2/cit_pagos/nuevo
Authorization: Bearer {{auth.response.body.access_token}}
content-type: application/json

{
    "nombres": "Paola",
    "apellido_primero": "Gonzalez",
    "apellido_segundo": "Mendoza",
    "curp": "LOVE770826MZSPGD55",
    "telefono": "8443331166",
    "email": "paola.gonzalez@gmail.com",
    "cit_tramite_servicio_id": 2,
    "cantidad": 2
}

### POST Pago antes del banco, ya ha hecho un pago antes, entrega el id del pago
POST {{baseUrl}}/v2/cit_pagos/nuevo
Authorization: Bearer {{auth.response.body.access_token}}
content-type: application/json

{
    "email": "paola.gonzalez@gmail.com",
    "cit_tramite_servicio_id": 3,
    "cantidad": 1
}

### POST Pago antes del banco, ya ha hecho un pago antes, entrega el id del pago
POST {{baseUrl}}/v2/cit_pagos/nuevo
Authorization: Bearer {{auth.response.body.access_token}}
content-type: application/json

{
    "email": "paola.gonzalez@gmail.com",
    "cit_tramite_servicio_id": 9,
    "cantidad": 4
}

### POST Pago despues del banco
POST {{baseUrl}}/v2/cit_pagos/realizado
Authorization: Bearer {{auth.response.body.access_token}}
content-type: application/json

{
    "id": 102,
    "folio": 3097984883,
    "estado": "REALIZADO",
}
